[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "omani-therapist-api"
source = "."

[services.healthcheck]
path = "/api/health"
timeout = 30
interval = 30

[services.variables]
PORT = "8000" 